-- Desktop base / folder support
create table if not exists public.desktop_folders (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    name text not null,
    created_at timestamptz not null default now()
);

alter table public.containers
    add column if not exists folder_id bigint references public.desktop_folders(id) on delete set null;

alter table public.desktop_folders enable row level security;

drop policy if exists "desktop folders own rows" on public.desktop_folders;
create policy "desktop folders own rows"
on public.desktop_folders for all to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

grant select, insert, update, delete on public.desktop_folders to authenticated;
grant usage, select on all sequences in schema public to authenticated;
