-- Loan / sale v2: mini-profiles, mutual-friend transfers, accepted returns.
-- RUN THIS FIRST in Supabase SQL Editor.

create table if not exists public.contacts (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    name text not null,
    phone text,
    notes text,
    created_at timestamptz not null default now()
);

alter table public.card_transactions
    add column if not exists contact_id bigint references public.contacts(id) on delete set null,
    add column if not exists current_borrower_id uuid references auth.users(id) on delete set null,
    add column if not exists return_status text,
    add column if not exists return_requested_at timestamptz;

update public.card_transactions
set current_borrower_id=friend_id
where transaction_type='loan' and current_borrower_id is null and friend_id is not null;

create table if not exists public.loan_transfers (
    id bigint generated by default as identity primary key,
    transaction_id bigint not null references public.card_transactions(id) on delete cascade,
    owner_id uuid not null references auth.users(id) on delete cascade,
    card_id text not null references public.card_catalog(id),
    from_user_id uuid references auth.users(id) on delete set null,
    to_user_id uuid references auth.users(id) on delete set null,
    quantity integer not null check(quantity>0),
    created_at timestamptz not null default now()
);

alter table public.contacts enable row level security;
alter table public.loan_transfers enable row level security;

drop policy if exists "contacts own rows" on public.contacts;
create policy "contacts own rows" on public.contacts
for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());

drop policy if exists "loan transfer participants read" on public.loan_transfers;
create policy "loan transfer participants read" on public.loan_transfers
for select to authenticated using(owner_id=auth.uid() or from_user_id=auth.uid() or to_user_id=auth.uid());

grant select,insert,update,delete on public.contacts to authenticated;
grant select on public.loan_transfers to authenticated;
grant usage,select on all sequences in schema public to authenticated;

create or replace function public.respond_to_card_offer(p_transaction_id bigint,p_accept boolean)
returns void language plpgsql security definer set search_path=public as $$
declare t public.card_transactions%rowtype; src public.collection_items%rowtype; buyer public.collection_items%rowtype;
begin
 select * into t from public.card_transactions where id=p_transaction_id for update;
 if not found then raise exception 'Offer not found'; end if;
 if t.friend_id<>auth.uid() then raise exception 'Only recipient can respond'; end if;
 if t.status<>'pending' then raise exception 'Offer is no longer pending'; end if;
 if not p_accept then update public.card_transactions set status='declined' where id=t.id; return; end if;
 select * into src from public.collection_items where id=t.source_item_id and user_id=t.owner_id
   and card_id=t.card_id and loaned_from_user_id is null for update;
 if not found or src.quantity<t.quantity then raise exception 'Not enough available copies'; end if;
 if t.transaction_type='loan' then
   update public.card_transactions set source_container_id=src.container_id,loan_condition=src.condition,
     loan_foil=src.foil,lender_inventory_removed=true,current_borrower_id=t.friend_id,return_status=null where id=t.id;
   if src.quantity=t.quantity then delete from public.collection_items where id=src.id;
   else update public.collection_items set quantity=quantity-t.quantity where id=src.id; end if;
   insert into public.collection_items(user_id,card_id,quantity,condition,foil,container_id,is_missing,
     loaned_from_user_id,loan_transaction_id)
   values(t.friend_id,t.card_id,t.quantity,src.condition,src.foil,null,false,t.owner_id,t.id);
 elsif t.transaction_type='sale' then
   if src.quantity=t.quantity then delete from public.collection_items where id=src.id;
   else update public.collection_items set quantity=quantity-t.quantity where id=src.id; end if;
   select * into buyer from public.collection_items where user_id=t.friend_id and card_id=t.card_id
     and container_id is null and is_missing=false and loaned_from_user_id is null
     and condition is not distinct from src.condition and foil is not distinct from src.foil limit 1 for update;
   if found then update public.collection_items set quantity=quantity+t.quantity where id=buyer.id;
   else insert into public.collection_items(user_id,card_id,quantity,condition,foil,container_id,is_missing)
     values(t.friend_id,t.card_id,t.quantity,src.condition,src.foil,null,false); end if;
 else raise exception 'Unknown transaction type'; end if;
 update public.card_transactions set status='accepted' where id=t.id;
end $$;

create or replace function public.transfer_borrowed_loan(p_transaction_id bigint,p_new_borrower_id uuid)
returns void language plpgsql security definer set search_path=public as $$
declare t public.card_transactions%rowtype; borrowed public.collection_items%rowtype; a uuid; b uuid;
begin
 select * into t from public.card_transactions where id=p_transaction_id and transaction_type='loan'
   and status='accepted' and returned_at is null for update;
 if not found then raise exception 'Active loan not found'; end if;
 if coalesce(t.current_borrower_id,t.friend_id)<>auth.uid() then raise exception 'Only current borrower can transfer'; end if;
 if p_new_borrower_id=t.owner_id or p_new_borrower_id=auth.uid() then raise exception 'Invalid borrower'; end if;
 a:=least(auth.uid(),p_new_borrower_id); b:=greatest(auth.uid(),p_new_borrower_id);
 if not exists(select 1 from public.friendships where user_a=a and user_b=b and status='accepted')
   then raise exception 'New borrower must be your friend'; end if;
 a:=least(t.owner_id,p_new_borrower_id); b:=greatest(t.owner_id,p_new_borrower_id);
 if not exists(select 1 from public.friendships where user_a=a and user_b=b and status='accepted')
   then raise exception 'New borrower must also be a friend of the owner'; end if;
 select * into borrowed from public.collection_items where loan_transaction_id=t.id and user_id=auth.uid() limit 1 for update;
 if not found then raise exception 'Borrowed card not found'; end if;
 update public.collection_items set user_id=p_new_borrower_id where id=borrowed.id;
 insert into public.loan_transfers(transaction_id,owner_id,card_id,from_user_id,to_user_id,quantity)
 values(t.id,t.owner_id,t.card_id,auth.uid(),p_new_borrower_id,t.quantity);
 update public.card_transactions set current_borrower_id=p_new_borrower_id,return_status=null,return_requested_at=null where id=t.id;
end $$;

create or replace function public.request_loan_return(p_transaction_id bigint)
returns void language plpgsql security definer set search_path=public as $$
declare t public.card_transactions%rowtype;
begin
 select * into t from public.card_transactions where id=p_transaction_id and transaction_type='loan'
   and status='accepted' and returned_at is null for update;
 if not found then raise exception 'Active loan not found'; end if;
 if t.contact_id is not null then raise exception 'Owner confirms non-user returns'; end if;
 if coalesce(t.current_borrower_id,t.friend_id)<>auth.uid() then raise exception 'Only current borrower can request return'; end if;
 update public.card_transactions set return_status='requested',return_requested_at=now() where id=t.id;
end $$;

create or replace function public.respond_to_return_request(p_transaction_id bigint,p_accept boolean)
returns void language plpgsql security definer set search_path=public as $$
declare t public.card_transactions%rowtype; borrowed public.collection_items%rowtype;
 owner_item public.collection_items%rowtype; target_container bigint;
begin
 select * into t from public.card_transactions where id=p_transaction_id and transaction_type='loan'
   and status='accepted' and returned_at is null for update;
 if not found then raise exception 'Active loan not found'; end if;
 if t.owner_id<>auth.uid() then raise exception 'Only owner can confirm return'; end if;
 if t.return_status<>'requested' then raise exception 'No return request pending'; end if;
 if not p_accept then update public.card_transactions set return_status='declined' where id=t.id; return; end if;
 select * into borrowed from public.collection_items where loan_transaction_id=t.id
   and user_id=coalesce(t.current_borrower_id,t.friend_id) limit 1 for update;
 target_container:=null;
 if t.source_container_id is not null and exists(select 1 from public.containers where id=t.source_container_id and user_id=t.owner_id)
   then target_container:=t.source_container_id; end if;
 select * into owner_item from public.collection_items where user_id=t.owner_id and card_id=t.card_id
   and container_id is not distinct from target_container and is_missing=false and loaned_from_user_id is null
   and condition is not distinct from coalesce(t.loan_condition,borrowed.condition)
   and foil is not distinct from coalesce(t.loan_foil,borrowed.foil) limit 1 for update;
 if found then update public.collection_items set quantity=quantity+t.quantity where id=owner_item.id;
 else insert into public.collection_items(user_id,card_id,quantity,condition,foil,container_id,is_missing)
   values(t.owner_id,t.card_id,t.quantity,coalesce(t.loan_condition,borrowed.condition,'NM'),
     coalesce(t.loan_foil,borrowed.foil,false),target_container,false); end if;
 delete from public.collection_items where loan_transaction_id=t.id;
 update public.card_transactions set returned_at=now(),return_status='accepted' where id=t.id;
end $$;

create or replace function public.create_nonuser_transaction(
 p_contact_id bigint,p_source_item_id bigint,p_transaction_type text,p_quantity integer,p_price numeric default null
) returns bigint language plpgsql security definer set search_path=public as $$
declare src public.collection_items%rowtype; txid bigint;
begin
 if p_transaction_type not in ('loan','sale') or p_quantity<1 then raise exception 'Invalid transaction'; end if;
 if not exists(select 1 from public.contacts where id=p_contact_id and user_id=auth.uid()) then raise exception 'Contact not found'; end if;
 select * into src from public.collection_items where id=p_source_item_id and user_id=auth.uid()
   and loaned_from_user_id is null and is_missing=false for update;
 if not found or src.quantity<p_quantity then raise exception 'Not enough available copies'; end if;
 insert into public.card_transactions(owner_id,friend_id,contact_id,current_borrower_id,card_id,source_item_id,
   transaction_type,quantity,price,status,source_container_id,loan_condition,loan_foil,lender_inventory_removed)
 values(auth.uid(),null,p_contact_id,null,src.card_id,src.id,p_transaction_type,p_quantity,
   case when p_transaction_type='sale' then p_price else null end,'accepted',
   src.container_id,src.condition,src.foil,p_transaction_type='loan') returning id into txid;
 if src.quantity=p_quantity then delete from public.collection_items where id=src.id;
 else update public.collection_items set quantity=quantity-p_quantity where id=src.id; end if;
 return txid;
end $$;

create or replace function public.confirm_nonuser_return(p_transaction_id bigint)
returns void language plpgsql security definer set search_path=public as $$
declare t public.card_transactions%rowtype; owner_item public.collection_items%rowtype; target_container bigint;
begin
 select * into t from public.card_transactions where id=p_transaction_id and owner_id=auth.uid()
   and contact_id is not null and transaction_type='loan' and status='accepted' and returned_at is null for update;
 if not found then raise exception 'Active non-user loan not found'; end if;
 target_container:=null;
 if t.source_container_id is not null and exists(select 1 from public.containers where id=t.source_container_id and user_id=t.owner_id)
   then target_container:=t.source_container_id; end if;
 select * into owner_item from public.collection_items where user_id=t.owner_id and card_id=t.card_id
   and container_id is not distinct from target_container and is_missing=false and loaned_from_user_id is null
   and condition is not distinct from t.loan_condition and foil is not distinct from t.loan_foil limit 1 for update;
 if found then update public.collection_items set quantity=quantity+t.quantity where id=owner_item.id;
 else insert into public.collection_items(user_id,card_id,quantity,condition,foil,container_id,is_missing)
   values(t.owner_id,t.card_id,t.quantity,coalesce(t.loan_condition,'NM'),coalesce(t.loan_foil,false),target_container,false); end if;
 update public.card_transactions set returned_at=now(),return_status='accepted' where id=t.id;
end $$;

grant execute on function public.respond_to_card_offer(bigint,boolean) to authenticated;
grant execute on function public.transfer_borrowed_loan(bigint,uuid) to authenticated;
grant execute on function public.request_loan_return(bigint) to authenticated;
grant execute on function public.respond_to_return_request(bigint,boolean) to authenticated;
grant execute on function public.create_nonuser_transaction(bigint,bigint,text,integer,numeric) to authenticated;
grant execute on function public.confirm_nonuser_return(bigint) to authenticated;
